import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseAdmin } from '@/lib/supabase'

export const runtime = 'nodejs'

const CATEGORY_COLORS: Record<string, string> = {
  'technology': '#6366f1',
  'events-hospitality': '#f97316',
  'business-marketing': '#22c55e',
}

function buildNewsletterHtml(
  businessName: string,
  articles: Array<{ title: string; summary?: string | null; url: string; category?: string; source?: string }>
): string {
  const date = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

  const articlesHtml = articles.map((a) => {
    const catColor = CATEGORY_COLORS[a.category || ''] || '#6366f1'
    const catLabel = a.category === 'events-hospitality'
      ? 'Events & Hospitality'
      : a.category === 'business-marketing'
        ? 'Business & Marketing'
        : 'Technology'

    return `
      <div style="margin-bottom:32px;padding-bottom:32px;border-bottom:1px solid #e5e7eb;">
        <span style="display:inline-block;background:${catColor};color:#fff;font-size:11px;font-weight:600;padding:3px 10px;border-radius:20px;margin-bottom:10px;text-transform:uppercase;letter-spacing:0.5px;">${catLabel}</span>
        <h2 style="margin:0 0 10px;font-size:18px;font-weight:700;color:#111827;line-height:1.4;">${a.title}</h2>
        ${a.summary ? `<p style="margin:0 0 14px;color:#4b5563;font-size:15px;line-height:1.6;">${a.summary}</p>` : ''}
        ${a.source ? `<p style="margin:0 0 10px;color:#9ca3af;font-size:12px;">Source: ${a.source}</p>` : ''}
        <a href="${a.url}" style="color:${catColor};font-size:14px;font-weight:600;text-decoration:none;">Read more &rarr;</a>
      </div>
    `
  }).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${businessName} — News Digest</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;margin-top:24px;margin-bottom:24px;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1e1b4b 0%,#312e81 50%,#4338ca 100%);padding:40px 32px;text-align:center;">
      <h1 style="margin:0 0 6px;color:#fff;font-size:28px;font-weight:800;letter-spacing:-0.5px;">${businessName}</h1>
      <p style="margin:0;color:rgba(255,255,255,0.7);font-size:14px;">Weekly News Digest &bull; ${date}</p>
    </div>
    <!-- Content -->
    <div style="padding:40px 32px;">
      ${articlesHtml}
    </div>
    <!-- Footer -->
    <div style="background:#f3f4f6;padding:24px 32px;text-align:center;border-top:1px solid #e5e7eb;">
      <p style="margin:0 0 6px;color:#6b7280;font-size:13px;">You are receiving this because you subscribed to ${businessName} news updates.</p>
      <p style="margin:0;color:#9ca3af;font-size:12px;">Generated by Mission Control &bull; ${date}</p>
    </div>
  </div>
</body>
</html>`
}

export async function GET(req: NextRequest) {
  const supabase = createServerSupabaseAdmin()
  const { searchParams } = new URL(req.url)
  const business = searchParams.get('business')

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let query: any = supabase
    .from('newsletters')
    .select('*')
    .order('created_at', { ascending: false })

  if (business) query = query.eq('business', business)

  const { data, error } = await query.limit(20)

  if (error) {
    if (error.code === 'PGRST116' || error.message?.includes('does not exist') || error.code === '42P01') {
      return NextResponse.json({ ok: true, newsletters: [] })
    }
    return NextResponse.json({ ok: false, error: error.message, newsletters: [] })
  }

  return NextResponse.json({ ok: true, newsletters: data || [] })
}

export async function POST(req: NextRequest) {
  const supabase = createServerSupabaseAdmin()
  const body = await req.json()
  const { title, business, article_ids } = body

  if (!title || !business || !Array.isArray(article_ids) || article_ids.length === 0) {
    return NextResponse.json({ ok: false, error: 'title, business, and article_ids required' }, { status: 400 })
  }

  // Fetch the articles
  const { data: articles, error: articlesError } = await supabase
    .from('news_articles')
    .select('*')
    .in('id', article_ids)

  if (articlesError) {
    return NextResponse.json({ ok: false, error: articlesError.message })
  }

  const articleList = articles || []

  // Find business display name
  const BUSINESSES: Record<string, string> = {
    barpeople: 'The Bar People',
    bookedevents: 'Booked Events',
    futureclimbing: 'Future Climbing',
    anyos: 'anyOS',
  }
  const businessName = BUSINESSES[business] || business

  const html = buildNewsletterHtml(businessName, articleList)

  const { data: newsletter, error: insertError } = await supabase
    .from('newsletters')
    .insert({
      title,
      business,
      articles: articleList,
      html_content: html,
      status: 'draft',
    })
    .select()
    .single()

  if (insertError) {
    if (insertError.code === 'PGRST116' || insertError.message?.includes('does not exist') || insertError.code === '42P01') {
      // Table doesn't exist yet — return the HTML anyway so user can copy it
      return NextResponse.json({ ok: true, html, newsletter: null, warning: 'newsletters table not found, HTML generated but not saved' })
    }
    return NextResponse.json({ ok: false, error: insertError.message })
  }

  return NextResponse.json({ ok: true, html, newsletter })
}
